spring.application.name=CloudTestApplication

# Point to Cloud SQL via the proxy
spring.datasource.url=jdbc:mysql://awseb-e-3jc5i8mu8b-stack-awsebrdsdatabase-ohc0yr0lkx6z.cvuoio8gkhbh.us-east-2.rds.amazonaws.com:3306/awsactivity
spring.datasource.username=elijahkremer
spring.datasource.password=Ek240741!!!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server port for your Spring Boot app
server.port=${PORT:8080}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true