spring.application.name=CloudTestApplication

# Point to Cloud SQL via the proxy
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/cstactivity
spring.datasource.username=elijahk
spring.datasource.password=1qaz!QAZ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Server port for your Spring Boot app
server.port=${PORT:8080}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true