version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building Spring Boot app with Maven..."
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/cloud_test_app.jar